#!/bin/sh

bspc rule -r "*"

killall ~/.config/polybar/launch.sh --forest
killall sxhkd
killall picom
killall nm-applet
killall flameshot
killall udiskie

sxhkd &
~/.config/polybar/launch.sh --forest &
picom &
nm-applet &
nitrogen --restore &
flameshot &
udiskie &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        2
bspc config window_gap          4
bspc config top_padding         20
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move


#### BSPWM coloring ####
bspc config normal_border_color		      "#131721"
bspc config active_border_color	          "#aad94c"
bspc config focused_border_color	      "#aad94c"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^3', state=monocle follow=on
bspc rule -a Zathura  state=tiled follow=on
bspc rule -a Screenkey manage=off
