#!/bin/sh

bspc rule -r "*"

killall polybar example
killall sxhkd
killall dunst
killall picom
killall udiskie
killall nm-applet
killall optimus-manager-qt

sxhkd &
polybar example &
picom &
dunst &
udiskie &
optimus-manager-qt &
nm-applet &
nitrogen --restore &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          5
bspc config top_padding         32
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

#### BSPWM coloring ####
bspc config normal_border_color		      "#282c34"
bspc config active_border_color	          "#e06c75"
bspc config focused_border_color	      "#e06c75"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^3', state=monocle follow=on
bspc rule -a Zathura  state=tiled follow=on
bspc rule -a Screenkey manage=off
