rsync -ra /home/robovoid/.config/qtile /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/nvim /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/alacritty /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/ranger/rc.conf /home/robovoid/dot-files/ranger/ &
rsync -ra /home/robovoid/.config/ranger/rifle.conf /home/robovoid/dot-files/ranger/ &
rsync -ra /home/robovoid/.zshrc /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/compton /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/dunst /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/scripts /home/robovoid/dot-files/ &
