rsync -ra /home/robovoid/.config/qtile /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/nvim /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/alacritty /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/ranger /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.zshrc /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/picom.conf /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/dunst /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/scripts /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/bspwm /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/polybar /home/robovoid/dot-files/ &
rsync -ra /home/robovoid/.config/sxhkd /home/robovoid/dot-files/ &
