#!/usr/bin/python
import subprocess
choice = subprocess.check_output('echo -e "shutdown\nsuspend\nrestart" | rofi -dmenu -p "Shutdown/Suspend"', shell=True, universal_newlines=True)
if choice == "shutdown\n":
    subprocess.call("systemctl poweroff", shell=True)
elif choice == "suspend\n":
    subprocess.call("systemctl suspend", shell=True)
elif choice == "restart\n":
    subprocess.call("systemctl restart", shell=True)

